# Base configs
baseurl: "https://em4volts.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "PATTERNS"
subtitle: ""
author: "EM4V"
header:
 title: "PATTERNS"
 subtitle: "by EM4V     click PATTERNS to view full size versions"
footer:
 name: "Hey there, my name is 4V"
 bio: "Im a rando from Germany.   All images here are provided under the <a href=\"https://creativecommons.org/licenses/by-nc/3.0\">CC BY-NC 3.0</a> License, if an image takes long to load just wait, theyre quite big." 
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/em4v2"
  youtube: "https://www.youtube.com/@fourthvolt8209"
  github: "https://www.github.com/em4volts"
